const Utils = require('../client/Utils')

module.exports = Utils.createEnum({    
    ThreadMemberNicknameUpdate: 'threadMemberNicknameUpdate',
    ThreadApprovalModeOff: 'threadApprovalModeOff',
    MessageReactionRemove: 'messageReactionRemove',
    ThreadApprovalModeOn: 'threadApprovalModeOn',
    MessageReactionAdd: 'messageReactionAdd',
    ThreadMemberRemove: 'threadMemberRemove',
    ThreadColorUpdate: 'threadColorUpdate',
    ThreadEmojiUpdate: 'threadEmojiUpdate',
    ThreadAdminRemove: 'threadAdminRemove',
    ThreadImageUpdate: 'threadImageUpdate',
    ThreadPollCreate: 'threadPollCreate',
    ThreadPollUpdate: 'threadPollUpdate',
    ThreadMemberAdd: 'threadMemberAdd',
    ThreadCallStart: 'threadCallStart',
    ThreadAdminAdd: 'threadAdminAdd',
    ThreadCallJoin: 'threadCallJoin',
    ThreadCallEnd: 'threadCallEnd',
    MessageTyping: 'messageTyping',
    MessageCreate: 'messageCreate',
    MessageDelete: 'messageDelete',
    ThreadCallEnd: 'threadCallEnd',
    MessageReply: 'messageReply',
    ThreadRename: 'threadRename',
    GroupLeave: 'groupLeave',
    GroupJoin: 'groupJoin',
    UserRead: 'userRead',

    Ready: 'ready',
    Error: 'error',
    Debug: 'debug',
})